services:
  - type: web
    name: finalfrontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: YOUR_BACKEND_URL_HERE/api